### ISSUE TITLE
The length mapper does not work with the body mapper

### ISSUE THREAD

**Issue by nickelc** [ggriffiniii/httptest#1]
I'm working on a PR to add more examples to the doc comments. I tried to use the length mapper with `request::body()` but it does not work while it works fine with `request::query()`.

```rust
use http::Request;
use httptest::mappers::*;

let req = Request::get("/test?foo=bar").body("foobar").unwrap();
assert!(request::query(len(eq(7))).map(&req));
assert!(request::body(len(eq(6))).map(&req));
```

```
error[E0277]: expected a `std::ops::Fn<(&&str,)>` closure, found `httptest::mappers::Len<httptest::mappers::Eq<{integer}>>`
 --> src/main.rs:8:39
  |
8 |     assert!(request::body(len(eq(6))).map(&req));
  |                                       ^^^ expected an `Fn<(&&str,)>` closure, found `httptest::mappers::Len<httptest::mappers::Eq<{integer}>>`
  |
  = help: the trait `for<'r> std::ops::Fn<(&'r &str,)>` is not implemented for `httptest::mappers::Len<httptest::mappers::Eq<{integer}>>`
  = note: required because of the requirements on the impl of `httptest::mappers::Mapper<&str>` for `httptest::mappers::Len<httptest::mappers::Eq<{integer}>>`
  = note: required because of the requirements on the impl of `httptest::mappers::Mapper<http::request::Request<&str>>` for `httptest::mappers::request::Body<httptest::mappers::Len<httptest::mappers::Eq<{integer}>>>`
```

btw great library :+1:

**Comment by ggriffiniii** [comment]
Thanks for the update and for any additional documentation. I appreciate it. Sometimes it's hard to document your own library because you're so intimately familiar with it that it's difficult to know what needs to be elaborated so it's great to have a set of fresh eyes looking at it.

Regarding the issue the request::body mapper is tricky, I was trying to be clever by being generic over any possible body so long as there was a way to get an Owned version of it. Unfortunately, it didn't quite work out that way because references of references implement ToOwned but the result is just a single layer of deref, where we may need multiple deref's before we get to a concrete type that subsequent mappers are expecting. I opted instead to just write the body mapper for the common types that people will be encountering in unit tests &str, &[u8], and Vec<u8>. Hopefully, this will be good enough for all practical use cases. This issue should be fixed by https://github.com/ggriffiniii/httptest/commit/331ab9bdb40ac6f7f91bfe4518afe2c36180ba34 and pushed as the latest version to crates.io now. I'm going to close the issue, but feel free to open any other issues you encounter, I appreciate the feedback.
