### ISSUE TITLE
Add changelog or release notes

### ISSUE THREAD

**Issue by tjkirch** [ggriffiniii/httptest#15]
It would be great to have a changelog in the repo and/or release notes on the GitHub releases page. It would help users know the context of a release and what changes they might need to be aware of in relation to their own code.  Thanks!

**Comment by ggriffiniii** [comment]
Thanks for the feedback that's a good point. I'll do my best to include release notes going forward. In regards to the recently released v0.15.3 it was a very minor change that simply exposed the IntoTimes trait publicly so that users could refer to it from their own crates. This was requested in issue #14 if you're curious.
